// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcgu2I5ELGGagNZTSSTwI7AYuxMlOQG0Q',
    appId: '1:864780094281:web:0e9d475bad82d496502898',
    messagingSenderId: '864780094281',
    projectId: 'appfrankie-16bee',
    authDomain: 'appfrankie-16bee.firebaseapp.com',
    storageBucket: 'appfrankie-16bee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQWFyVzIBcEDmDjF3g6wKVFPaLyFLA5XI',
    appId: '1:864780094281:android:2f00fffc222c34c3502898',
    messagingSenderId: '864780094281',
    projectId: 'appfrankie-16bee',
    storageBucket: 'appfrankie-16bee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALzOJyvjJJm1U4g6Jt66Q_rw8OmOfbISw',
    appId: '1:864780094281:ios:38763293186b4d8e502898',
    messagingSenderId: '864780094281',
    projectId: 'appfrankie-16bee',
    storageBucket: 'appfrankie-16bee.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALzOJyvjJJm1U4g6Jt66Q_rw8OmOfbISw',
    appId: '1:864780094281:ios:38763293186b4d8e502898',
    messagingSenderId: '864780094281',
    projectId: 'appfrankie-16bee',
    storageBucket: 'appfrankie-16bee.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcgu2I5ELGGagNZTSSTwI7AYuxMlOQG0Q',
    appId: '1:864780094281:web:e4986bd5baa68046502898',
    messagingSenderId: '864780094281',
    projectId: 'appfrankie-16bee',
    authDomain: 'appfrankie-16bee.firebaseapp.com',
    storageBucket: 'appfrankie-16bee.firebasestorage.app',
  );
}
